### ISSUE TITLE
Domain Parameter options

### ISSUE THREAD

**Issue by hymanjd** [aidanstansberry/dfnWorks#2]
For pydfnWorks it would be nice to not have users use integers for options. For example

DFN.params['rAngleOption']['value'] = 1
DFN.params['orientationOption']['value'] = 1

Could be

DFN.params['rAngleOption']['value'] = 'degree'
DFN.params['orientationOption']['value'] = 'trend_plunge'

And then we convert those to what DFNGen expects behind the scenes. I think this would be easier for users to interact with.

**Comment by aidanstansberry** [comment]
Changes worked well with TPL example. 
1) DFN.params['orientationOption']['value'] no longer needs to be defined. 
2) prefix removed from 'angleOption'
3) DFN.params['angleOption']['value'] = 'degree' or 'radian'.
